spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    platform: mysql
    initialize: true